// Enroll Course Constants
export const ENROLL_COURSE_REQUEST = 'ENROLL_COURSE_REQUEST';
export const ENROLL_COURSE_SUCCESS = 'ENROLL_COURSE_SUCCESS';
export const ENROLL_COURSE_FAIL = 'ENROLL_COURSE_FAIL';
export const ENROLL_COURSE_RESET = 'ENROLL_COURSE_RESET';

// Enroll Based on Trending Issue Constants
export const ENROLL_BASED_ON_TRENDING_ISSUE_REQUEST = 'ENROLL_BASED_ON_TRENDING_ISSUE_REQUEST';
export const ENROLL_BASED_ON_TRENDING_ISSUE_SUCCESS = 'ENROLL_BASED_ON_TRENDING_ISSUE_SUCCESS';
export const ENROLL_BASED_ON_TRENDING_ISSUE_FAIL = 'ENROLL_BASED_ON_TRENDING_ISSUE_FAIL';
export const ENROLL_BASED_ON_TRENDING_ISSUE_RESET = 'ENROLL_BASED_ON_TRENDING_ISSUE_RESET';

// Unenroll Course Constants
export const UNENROLL_COURSE_REQUEST = 'UNENROLL_COURSE_REQUEST';
export const UNENROLL_COURSE_SUCCESS = 'UNENROLL_COURSE_SUCCESS';
export const UNENROLL_COURSE_FAIL = 'UNENROLL_COURSE_FAIL';
export const UNENROLL_COURSE_RESET = 'UNENROLL_COURSE_RESET';

// Course Detail Constants
export const COURSE_DETAIL_REQUEST = 'COURSE_DETAIL_REQUEST';
export const COURSE_DETAIL_SUCCESS = 'COURSE_DETAIL_SUCCESS';
export const COURSE_DETAIL_FAIL = 'COURSE_DETAIL_FAIL';
export const COURSE_DETAIL_RESET = 'COURSE_DETAIL_RESET';

// Course List Constants
export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST';
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS';
export const COURSE_LIST_FAIL = 'COURSE_LIST_FAIL';
export const COURSE_LIST_RESET = 'COURSE_LIST_RESET';

// Comment on Finance Constants
export const COMMENT_ON_FINANCE_REQUEST = 'COMMENT_ON_FINANCE_REQUEST';
export const COMMENT_ON_FINANCE_SUCCESS = 'COMMENT_ON_FINANCE_SUCCESS';
export const COMMENT_ON_FINANCE_FAIL = 'COMMENT_ON_FINANCE_FAIL';
export const COMMENT_ON_FINANCE_RESET = 'COMMENT_ON_FINANCE_RESET';

// Reply to Comment Constants
export const REPLY_TO_COMMENT_REQUEST = 'REPLY_TO_COMMENT_REQUEST';
export const REPLY_TO_COMMENT_SUCCESS = 'REPLY_TO_COMMENT_SUCCESS';
export const REPLY_TO_COMMENT_FAIL = 'REPLY_TO_COMMENT_FAIL';
export const REPLY_TO_COMMENT_RESET = 'REPLY_TO_COMMENT_RESET';

// Delete Comment Constants
export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';
export const DELETE_COMMENT_RESET = 'DELETE_COMMENT_RESET';

// Update Comment Constants
export const UPDATE_COMMENT_REQUEST = 'UPDATE_COMMENT_REQUEST';
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS';
export const UPDATE_COMMENT_FAIL = 'UPDATE_COMMENT_FAIL';
export const UPDATE_COMMENT_RESET = 'UPDATE_COMMENT_RESET';

// Finance Detail Constants
export const FINANCE_DETAIL_REQUEST = 'FINANCE_DETAIL_REQUEST';
export const FINANCE_DETAIL_SUCCESS = 'FINANCE_DETAIL_SUCCESS';
export const FINANCE_DETAIL_FAIL = 'FINANCE_DETAIL_FAIL';
export const FINANCE_DETAIL_RESET = 'FINANCE_DETAIL_RESET';

// Finance List Constants
export const FINANCE_LIST_REQUEST = 'FINANCE_LIST_REQUEST';
export const FINANCE_LIST_SUCCESS = 'FINANCE_LIST_SUCCESS';
export const FINANCE_LIST_FAIL = 'FINANCE_LIST_FAIL';
export const FINANCE_LIST_RESET = 'FINANCE_LIST_RESET';

// Trending Issue List Constants
export const TRENDING_ISSUE_LIST_REQUEST = 'TRENDING_ISSUE_LIST_REQUEST';
export const TRENDING_ISSUE_LIST_SUCCESS = 'TRENDING_ISSUE_LIST_SUCCESS';
export const TRENDING_ISSUE_LIST_FAIL = 'TRENDING_ISSUE_LIST_FAIL';
export const TRENDING_ISSUE_LIST_RESET = 'TRENDING_ISSUE_LIST_RESET';

// Trending Issue Detail Constants
export const TRENDING_ISSUE_DETAIL_REQUEST = 'TRENDING_ISSUE_DETAIL_REQUEST';
export const TRENDING_ISSUE_DETAIL_SUCCESS = 'TRENDING_ISSUE_DETAIL_SUCCESS';
export const TRENDING_ISSUE_DETAIL_FAIL = 'TRENDING_ISSUE_DETAIL_FAIL';
export const TRENDING_ISSUE_DETAIL_RESET = 'TRENDING_ISSUE_DETAIL_RESET';

// Prediction List Constants
export const PREDICTION_LIST_REQUEST = 'PREDICTION_LIST_REQUEST';
export const PREDICTION_LIST_SUCCESS = 'PREDICTION_LIST_SUCCESS';
export const PREDICTION_LIST_FAIL = 'PREDICTION_LIST_FAIL';
export const PREDICTION_LIST_RESET = 'PREDICTION_LIST_RESET';

// Notification List Constants
export const NOTIFICATION_LIST_REQUEST = 'NOTIFICATION_LIST_REQUEST';
export const NOTIFICATION_LIST_SUCCESS = 'NOTIFICATION_LIST_SUCCESS';
export const NOTIFICATION_LIST_FAIL = 'NOTIFICATION_LIST_FAIL';
export const NOTIFICATION_LIST_RESET = 'NOTIFICATION_LIST_RESET';
